cmake_minimum_required(VERSION 4.3)
project(Temperature_Humidity_Sensor_Alarm_System C)

set(CMAKE_C_STANDARD 11)

include_directories(.)
include_directories(FreeRTOS/Source/include)
include_directories(FreeRTOS/Source/portable/RVDS/ARM_CM3)
include_directories(Hardware)
include_directories(Library)
include_directories(Start)
include_directories(System)
include_directories(Tasks)
include_directories(User)

add_executable(Temperature_Humidity_Sensor_Alarm_System
        FreeRTOS/Source/include/atomic.h
        FreeRTOS/Source/include/croutine.h
        FreeRTOS/Source/include/deprecated_definitions.h
        FreeRTOS/Source/include/event_groups.h
        FreeRTOS/Source/include/FreeRTOS.h
        FreeRTOS/Source/include/FreeRTOSConfig_template.h
        FreeRTOS/Source/include/list.h
        FreeRTOS/Source/include/message_buffer.h
        FreeRTOS/Source/include/mpu_prototypes.h
        FreeRTOS/Source/include/mpu_wrappers.h
        FreeRTOS/Source/include/portable.h
        FreeRTOS/Source/include/projdefs.h
        FreeRTOS/Source/include/queue.h
        FreeRTOS/Source/include/semphr.h
        FreeRTOS/Source/include/stack_macros.h
        FreeRTOS/Source/include/StackMacros.h
        FreeRTOS/Source/include/stream_buffer.h
        FreeRTOS/Source/include/task.h
        FreeRTOS/Source/include/timers.h
        FreeRTOS/Source/portable/MemMang/heap_4.c
        FreeRTOS/Source/portable/RVDS/ARM_CM3/port.c
        FreeRTOS/Source/portable/RVDS/ARM_CM3/portmacro.h
        FreeRTOS/Source/event_groups.c
        FreeRTOS/Source/list.c
        FreeRTOS/Source/queue.c
        FreeRTOS/Source/stream_buffer.c
        FreeRTOS/Source/tasks.c
        FreeRTOS/Source/timers.c
        Hardware/buzzer.c
        Hardware/buzzer.h
        Hardware/Key.c
        Hardware/Key.h
        Hardware/LED.c
        Hardware/LED.h
        Hardware/OLED.c
        Hardware/OLED.h
        Hardware/OLED_Font.h
        Library/misc.c
        Library/misc.h
        Library/stm32f10x_adc.c
        Library/stm32f10x_adc.h
        Library/stm32f10x_bkp.c
        Library/stm32f10x_bkp.h
        Library/stm32f10x_can.c
        Library/stm32f10x_can.h
        Library/stm32f10x_cec.c
        Library/stm32f10x_cec.h
        Library/stm32f10x_crc.c
        Library/stm32f10x_crc.h
        Library/stm32f10x_dac.c
        Library/stm32f10x_dac.h
        Library/stm32f10x_dbgmcu.c
        Library/stm32f10x_dbgmcu.h
        Library/stm32f10x_dma.c
        Library/stm32f10x_dma.h
        Library/stm32f10x_exti.c
        Library/stm32f10x_exti.h
        Library/stm32f10x_flash.c
        Library/stm32f10x_flash.h
        Library/stm32f10x_fsmc.c
        Library/stm32f10x_fsmc.h
        Library/stm32f10x_gpio.c
        Library/stm32f10x_gpio.h
        Library/stm32f10x_i2c.c
        Library/stm32f10x_i2c.h
        Library/stm32f10x_iwdg.c
        Library/stm32f10x_iwdg.h
        Library/stm32f10x_pwr.c
        Library/stm32f10x_pwr.h
        Library/stm32f10x_rcc.c
        Library/stm32f10x_rcc.h
        Library/stm32f10x_rtc.c
        Library/stm32f10x_rtc.h
        Library/stm32f10x_sdio.c
        Library/stm32f10x_sdio.h
        Library/stm32f10x_spi.c
        Library/stm32f10x_spi.h
        Library/stm32f10x_tim.c
        Library/stm32f10x_tim.h
        Library/stm32f10x_usart.c
        Library/stm32f10x_usart.h
        Library/stm32f10x_wwdg.c
        Library/stm32f10x_wwdg.h
        Start/core_cm3.c
        Start/core_cm3.h
        Start/stm32f10x.h
        Start/system_stm32f10x.c
        Start/system_stm32f10x.h
        System/alarm.c
        System/alarm.h
        System/Delay.c
        System/Delay.h
        System/dht11.c
        System/dht11.h
        System/Record_storage.c
        System/Record_storage.h
        System/UI.c
        System/UI.h
        System/USART.c
        System/USART.h
        System/warning_system.c
        System/warning_system.h
        Tasks/task_display.c
        Tasks/task_display.h
        Tasks/task_sensor.c
        Tasks/task_sensor.h
        User/FreeRTOSConfig.h
        User/main.c
        User/stm32f10x_conf.h
        User/stm32f10x_it.c
        User/stm32f10x_it.h
        User/stm32f10x_it_old.c
        Tasks/task_alarm.c
        Tasks/task_alarm.h
)
